pipeline {

    agent any
    stages {
        stage('Clone') {
            steps {
                    git 'https://github.com/nadergan/simple-maven-project-with-tests.git'
            }
        }

        stage('Build') {
            steps{
                sh "./mvnw -Dmaven.test.failure.ignore=true clean package"
            }
        }

        stage('Run'){
            steps{
                sh "./mvnw spring-boot:run"
            }
        }

        stage('Artifact') {
            steps{
                archiveArtifacts artifacts: '**/*.jar', followSymlinks: false
            }
        }

    }
}